# Site settings
name: WCL 的 Blog
email: wnarry1996@gmail.com
author: WCL
url: http://xiaokedada.com
resume_site: http://xiaokedada.com/me/
github: 
baseurl: "https://wnarrylulu.github.io/aaa.github.io/"  #根目录
description: A
motto: B。
#motto: 如果生活欺骗了你，不要悲伤，不要哭泣。
banner: C
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: 
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : 
